events {}

http {

    upstream rent_auth_module {
        server auth:3001;
    }

    upstream rent_financial_module {
        server financial:3002;
    }

    server {

        listen 3000;

        location /rent-auth/ {
            proxy_pass http://rent_auth_module;
        }

        location /rent-financial/ {
            proxy_pass http://rent_financial_module;
        }

    }

}   